language: python
python:
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
# command to run tests
env:
  - DJANGO_VERSION=2.1.2